package Classes;
// Generated 30/03/2015 20:03:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String cpfCliente;
     private String nomeCliente;
     private String telefoneCliente;
     private String celularCliente;
     private String ruaCliente;
     private String numeroCasaCliente;
     private String estadoCliente;
     private String complementoCliente;
     private String cepCliente;
     private String emailCliente;
     private String bairroCliente;
     private String cidadeCliente;
     private Set vendaProdutos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String cpfCliente, String nomeCliente, String ruaCliente, String numeroCasaCliente, String estadoCliente, String complementoCliente, String cepCliente, String bairroCliente, String cidadeCliente) {
        this.cpfCliente = cpfCliente;
        this.nomeCliente = nomeCliente;
        this.ruaCliente = ruaCliente;
        this.numeroCasaCliente = numeroCasaCliente;
        this.estadoCliente = estadoCliente;
        this.complementoCliente = complementoCliente;
        this.cepCliente = cepCliente;
        this.bairroCliente = bairroCliente;
        this.cidadeCliente = cidadeCliente;
    }
    public Cliente(String cpfCliente, String nomeCliente, String telefoneCliente, String celularCliente, String ruaCliente, String numeroCasaCliente, String estadoCliente, String complementoCliente, String cepCliente, String emailCliente, String bairroCliente, String cidadeCliente, Set vendaProdutos) {
       this.cpfCliente = cpfCliente;
       this.nomeCliente = nomeCliente;
       this.telefoneCliente = telefoneCliente;
       this.celularCliente = celularCliente;
       this.ruaCliente = ruaCliente;
       this.numeroCasaCliente = numeroCasaCliente;
       this.estadoCliente = estadoCliente;
       this.complementoCliente = complementoCliente;
       this.cepCliente = cepCliente;
       this.emailCliente = emailCliente;
       this.bairroCliente = bairroCliente;
       this.cidadeCliente = cidadeCliente;
       this.vendaProdutos = vendaProdutos;
    }
   
    public String getCpfCliente() {
        return this.cpfCliente;
    }
    
    public void setCpfCliente(String cpfCliente) {
        this.cpfCliente = cpfCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getTelefoneCliente() {
        return this.telefoneCliente;
    }
    
    public void setTelefoneCliente(String telefoneCliente) {
        this.telefoneCliente = telefoneCliente;
    }
    public String getCelularCliente() {
        return this.celularCliente;
    }
    
    public void setCelularCliente(String celularCliente) {
        this.celularCliente = celularCliente;
    }
    public String getRuaCliente() {
        return this.ruaCliente;
    }
    
    public void setRuaCliente(String ruaCliente) {
        this.ruaCliente = ruaCliente;
    }
    public String getNumeroCasaCliente() {
        return this.numeroCasaCliente;
    }
    
    public void setNumeroCasaCliente(String numeroCasaCliente) {
        this.numeroCasaCliente = numeroCasaCliente;
    }
    public String getEstadoCliente() {
        return this.estadoCliente;
    }
    
    public void setEstadoCliente(String estadoCliente) {
        this.estadoCliente = estadoCliente;
    }
    public String getComplementoCliente() {
        return this.complementoCliente;
    }
    
    public void setComplementoCliente(String complementoCliente) {
        this.complementoCliente = complementoCliente;
    }
    public String getCepCliente() {
        return this.cepCliente;
    }
    
    public void setCepCliente(String cepCliente) {
        this.cepCliente = cepCliente;
    }
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }
    public String getBairroCliente() {
        return this.bairroCliente;
    }
    
    public void setBairroCliente(String bairroCliente) {
        this.bairroCliente = bairroCliente;
    }
    public String getCidadeCliente() {
        return this.cidadeCliente;
    }
    
    public void setCidadeCliente(String cidadeCliente) {
        this.cidadeCliente = cidadeCliente;
    }
    public Set getVendaProdutos() {
        return this.vendaProdutos;
    }
    
    public void setVendaProdutos(Set vendaProdutos) {
        this.vendaProdutos = vendaProdutos;
    }




}


