package Classes;
// Generated 30/03/2015 20:03:51 by Hibernate Tools 4.3.1



/**
 * CompraProduto generated by hbm2java
 */
public class CompraProduto  implements java.io.Serializable {


     private int codCompra;
     private Fornecedor fornecedor;
     private Funcionario funcionario;
     private Livro livro;

    public CompraProduto() {
    }

    public CompraProduto(int codCompra, Fornecedor fornecedor, Funcionario funcionario, Livro livro) {
       this.codCompra = codCompra;
       this.fornecedor = fornecedor;
       this.funcionario = funcionario;
       this.livro = livro;
    }
   
    public int getCodCompra() {
        return this.codCompra;
    }
    
    public void setCodCompra(int codCompra) {
        this.codCompra = codCompra;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }




}


