package Classes;
// Generated 30/03/2015 20:03:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private String cnpjFornecedor;
     private String nomeFornecedor;
     private String telefoneFornecedor;
     private String celulaFornecedor;
     private String ruaFornecedor;
     private String numerFornecedor;
     private String estadoFornecedor;
     private String complementoFornecedor;
     private String cepFornecedor;
     private String emailFornecedor;
     private String bairroFornecedor;
     private String cidadeFornecedor;
     private Set compraProdutos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(String cnpjFornecedor, String nomeFornecedor, String ruaFornecedor, String numerFornecedor, String estadoFornecedor, String complementoFornecedor, String cepFornecedor, String bairroFornecedor, String cidadeFornecedor) {
        this.cnpjFornecedor = cnpjFornecedor;
        this.nomeFornecedor = nomeFornecedor;
        this.ruaFornecedor = ruaFornecedor;
        this.numerFornecedor = numerFornecedor;
        this.estadoFornecedor = estadoFornecedor;
        this.complementoFornecedor = complementoFornecedor;
        this.cepFornecedor = cepFornecedor;
        this.bairroFornecedor = bairroFornecedor;
        this.cidadeFornecedor = cidadeFornecedor;
    }
    public Fornecedor(String cnpjFornecedor, String nomeFornecedor, String telefoneFornecedor, String celulaFornecedor, String ruaFornecedor, String numerFornecedor, String estadoFornecedor, String complementoFornecedor, String cepFornecedor, String emailFornecedor, String bairroFornecedor, String cidadeFornecedor, Set compraProdutos) {
       this.cnpjFornecedor = cnpjFornecedor;
       this.nomeFornecedor = nomeFornecedor;
       this.telefoneFornecedor = telefoneFornecedor;
       this.celulaFornecedor = celulaFornecedor;
       this.ruaFornecedor = ruaFornecedor;
       this.numerFornecedor = numerFornecedor;
       this.estadoFornecedor = estadoFornecedor;
       this.complementoFornecedor = complementoFornecedor;
       this.cepFornecedor = cepFornecedor;
       this.emailFornecedor = emailFornecedor;
       this.bairroFornecedor = bairroFornecedor;
       this.cidadeFornecedor = cidadeFornecedor;
       this.compraProdutos = compraProdutos;
    }
   
    public String getCnpjFornecedor() {
        return this.cnpjFornecedor;
    }
    
    public void setCnpjFornecedor(String cnpjFornecedor) {
        this.cnpjFornecedor = cnpjFornecedor;
    }
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public String getTelefoneFornecedor() {
        return this.telefoneFornecedor;
    }
    
    public void setTelefoneFornecedor(String telefoneFornecedor) {
        this.telefoneFornecedor = telefoneFornecedor;
    }
    public String getCelulaFornecedor() {
        return this.celulaFornecedor;
    }
    
    public void setCelulaFornecedor(String celulaFornecedor) {
        this.celulaFornecedor = celulaFornecedor;
    }
    public String getRuaFornecedor() {
        return this.ruaFornecedor;
    }
    
    public void setRuaFornecedor(String ruaFornecedor) {
        this.ruaFornecedor = ruaFornecedor;
    }
    public String getNumerFornecedor() {
        return this.numerFornecedor;
    }
    
    public void setNumerFornecedor(String numerFornecedor) {
        this.numerFornecedor = numerFornecedor;
    }
    public String getEstadoFornecedor() {
        return this.estadoFornecedor;
    }
    
    public void setEstadoFornecedor(String estadoFornecedor) {
        this.estadoFornecedor = estadoFornecedor;
    }
    public String getComplementoFornecedor() {
        return this.complementoFornecedor;
    }
    
    public void setComplementoFornecedor(String complementoFornecedor) {
        this.complementoFornecedor = complementoFornecedor;
    }
    public String getCepFornecedor() {
        return this.cepFornecedor;
    }
    
    public void setCepFornecedor(String cepFornecedor) {
        this.cepFornecedor = cepFornecedor;
    }
    public String getEmailFornecedor() {
        return this.emailFornecedor;
    }
    
    public void setEmailFornecedor(String emailFornecedor) {
        this.emailFornecedor = emailFornecedor;
    }
    public String getBairroFornecedor() {
        return this.bairroFornecedor;
    }
    
    public void setBairroFornecedor(String bairroFornecedor) {
        this.bairroFornecedor = bairroFornecedor;
    }
    public String getCidadeFornecedor() {
        return this.cidadeFornecedor;
    }
    
    public void setCidadeFornecedor(String cidadeFornecedor) {
        this.cidadeFornecedor = cidadeFornecedor;
    }
    public Set getCompraProdutos() {
        return this.compraProdutos;
    }
    
    public void setCompraProdutos(Set compraProdutos) {
        this.compraProdutos = compraProdutos;
    }




}


