package Classes;
// Generated 30/03/2015 20:03:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String cpfFuncionario;
     private String nomeFuncionario;
     private String telefoneFuncionario;
     private String celularFuncoionario;
     private String ruaFuncionario;
     private String numeroCasaFuncionario;
     private String estadoFuncionario;
     private String complementoFuncionario;
     private String cepFuncionario;
     private String emailFuncionario;
     private String bairroFuncionario;
     private String cidadeFuncionario;
     private String codFuncionario;
     private Set compraProdutos = new HashSet(0);
     private Set vendaProdutos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String cpfFuncionario, String nomeFuncionario, String ruaFuncionario, String numeroCasaFuncionario, String estadoFuncionario, String complementoFuncionario, String cepFuncionario, String bairroFuncionario, String cidadeFuncionario) {
        this.cpfFuncionario = cpfFuncionario;
        this.nomeFuncionario = nomeFuncionario;
        this.ruaFuncionario = ruaFuncionario;
        this.numeroCasaFuncionario = numeroCasaFuncionario;
        this.estadoFuncionario = estadoFuncionario;
        this.complementoFuncionario = complementoFuncionario;
        this.cepFuncionario = cepFuncionario;
        this.bairroFuncionario = bairroFuncionario;
        this.cidadeFuncionario = cidadeFuncionario;
    }
    public Funcionario(String cpfFuncionario, String nomeFuncionario, String telefoneFuncionario, String celularFuncoionario, String ruaFuncionario, String numeroCasaFuncionario, String estadoFuncionario, String complementoFuncionario, String cepFuncionario, String emailFuncionario, String bairroFuncionario, String cidadeFuncionario, String codFuncionario, Set compraProdutos, Set vendaProdutos) {
       this.cpfFuncionario = cpfFuncionario;
       this.nomeFuncionario = nomeFuncionario;
       this.telefoneFuncionario = telefoneFuncionario;
       this.celularFuncoionario = celularFuncoionario;
       this.ruaFuncionario = ruaFuncionario;
       this.numeroCasaFuncionario = numeroCasaFuncionario;
       this.estadoFuncionario = estadoFuncionario;
       this.complementoFuncionario = complementoFuncionario;
       this.cepFuncionario = cepFuncionario;
       this.emailFuncionario = emailFuncionario;
       this.bairroFuncionario = bairroFuncionario;
       this.cidadeFuncionario = cidadeFuncionario;
       this.codFuncionario = codFuncionario;
       this.compraProdutos = compraProdutos;
       this.vendaProdutos = vendaProdutos;
    }
   
    public String getCpfFuncionario() {
        return this.cpfFuncionario;
    }
    
    public void setCpfFuncionario(String cpfFuncionario) {
        this.cpfFuncionario = cpfFuncionario;
    }
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }
    public String getTelefoneFuncionario() {
        return this.telefoneFuncionario;
    }
    
    public void setTelefoneFuncionario(String telefoneFuncionario) {
        this.telefoneFuncionario = telefoneFuncionario;
    }
    public String getCelularFuncoionario() {
        return this.celularFuncoionario;
    }
    
    public void setCelularFuncoionario(String celularFuncoionario) {
        this.celularFuncoionario = celularFuncoionario;
    }
    public String getRuaFuncionario() {
        return this.ruaFuncionario;
    }
    
    public void setRuaFuncionario(String ruaFuncionario) {
        this.ruaFuncionario = ruaFuncionario;
    }
    public String getNumeroCasaFuncionario() {
        return this.numeroCasaFuncionario;
    }
    
    public void setNumeroCasaFuncionario(String numeroCasaFuncionario) {
        this.numeroCasaFuncionario = numeroCasaFuncionario;
    }
    public String getEstadoFuncionario() {
        return this.estadoFuncionario;
    }
    
    public void setEstadoFuncionario(String estadoFuncionario) {
        this.estadoFuncionario = estadoFuncionario;
    }
    public String getComplementoFuncionario() {
        return this.complementoFuncionario;
    }
    
    public void setComplementoFuncionario(String complementoFuncionario) {
        this.complementoFuncionario = complementoFuncionario;
    }
    public String getCepFuncionario() {
        return this.cepFuncionario;
    }
    
    public void setCepFuncionario(String cepFuncionario) {
        this.cepFuncionario = cepFuncionario;
    }
    public String getEmailFuncionario() {
        return this.emailFuncionario;
    }
    
    public void setEmailFuncionario(String emailFuncionario) {
        this.emailFuncionario = emailFuncionario;
    }
    public String getBairroFuncionario() {
        return this.bairroFuncionario;
    }
    
    public void setBairroFuncionario(String bairroFuncionario) {
        this.bairroFuncionario = bairroFuncionario;
    }
    public String getCidadeFuncionario() {
        return this.cidadeFuncionario;
    }
    
    public void setCidadeFuncionario(String cidadeFuncionario) {
        this.cidadeFuncionario = cidadeFuncionario;
    }
    public String getCodFuncionario() {
        return this.codFuncionario;
    }
    
    public void setCodFuncionario(String codFuncionario) {
        this.codFuncionario = codFuncionario;
    }
    public Set getCompraProdutos() {
        return this.compraProdutos;
    }
    
    public void setCompraProdutos(Set compraProdutos) {
        this.compraProdutos = compraProdutos;
    }
    public Set getVendaProdutos() {
        return this.vendaProdutos;
    }
    
    public void setVendaProdutos(Set vendaProdutos) {
        this.vendaProdutos = vendaProdutos;
    }




}


