package Classes;
// Generated 30/03/2015 20:03:51 by Hibernate Tools 4.3.1



/**
 * VendaProduto generated by hbm2java
 */
public class VendaProduto  implements java.io.Serializable {


     private int codVendaLivro;
     private Cliente cliente;
     private Funcionario funcionario;
     private Livro livro;

    public VendaProduto() {
    }

    public VendaProduto(int codVendaLivro, Cliente cliente, Funcionario funcionario, Livro livro) {
       this.codVendaLivro = codVendaLivro;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.livro = livro;
    }
   
    public int getCodVendaLivro() {
        return this.codVendaLivro;
    }
    
    public void setCodVendaLivro(int codVendaLivro) {
        this.codVendaLivro = codVendaLivro;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }




}


